name: CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Build architecture'
        required: true
        default: 'x64'
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  is-latest:
    name: "Is Latest"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
      - name: Check if latest
        working-directory: .github/workflows
        run: bash ./is_latest.sh ${{ github.event_name }}
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}


  build-linux:
    needs: [ is-latest ]
    name: "Build for Linux"
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20
      - name: Checkout code
        uses: actions/checkout@v4.1.7
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: npm install, build and test
        run: |
          npm install
          node build --arch x64 ${{ github.event.inputs.arch }}
      - name: Upload the artifacts
        uses: actions/upload-artifact@v4.3.6
        with:
          name: linux
          path: 'build/out/*.zip'

  build-release:
    needs: [ build-linux ]
    name: "Build Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Get NWJS version
        run: |
          echo "NW=$(curl -s https://nwjs.io/versions | jq -r '.latest' | sed 's/v//')" >> $GITHUB_ENV
          echo "CHROMIUM=$(curl -s https://nwjs.io/versions | jq -r '.versions[0].components.chromium')" >> $GITHUB_ENV

      - uses: actions/download-artifact@v4.1.8
        with:
          name: linux
          path: release/linux

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: release/

      - name: Upload linux binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/linux/*.zip
          tag: nwjs-ffmpeg-${{ env.NW }}
          body: Chromium ${{ env.CHROMIUM }}
          overwrite: true
          file_glob: true
